version: '3.8'
services:
  port-tech:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - mysql
    command: npm run start

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: porttechdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_container:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data_container:
